### ISSUE TITLE
IsADirectoryError: [Errno 21] Is a directory: './PA1450/PA1450-2021/application

### ISSUE THREAD

**Issue by JimBer110** [JimBer110/PA1450-2021#2]
**Commit: 236444ca3ef123146b8c19968210fde810bae717**
Issue when running `python3 main.py serve` in directory `application`

Output
```
 * Serving Flask app "commands.serve" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
 * Restarting with stat
Traceback (most recent call last):
  File "/home/jimmyb/Documents/Courses/PA1450/PA1450-2021/application/main.py", line 36, in <module>
    main()
  File "/home/jimmyb/Documents/Courses/PA1450/PA1450-2021/application/main.py", line 14, in main
    importer.downloadData()
  File "/home/jimmyb/Documents/Courses/PA1450/PA1450-2021/application/importer.py", line 129, in downloadData
    os.remove(os.path.join(myDir, f))
IsADirectoryError: [Errno 21] Is a directory: '/home/jimmyb/Documents/Courses/PA1450/PA1450-2021/application/covid_case_data/COVID-19-master'
```
System information
OS: Manjaro Linux x86_64

**Comment by kynkel** [comment]
I have changed the funktion so it should not crash anymore if data already exists
